logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/csof_test
  main:
    banner-mode: "off"

magnolia:
  url: https://magnolia.com
  feature: false

gui:
  disclaimer:
    background-color: red
    content: LOCAL

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

